sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ddocker16/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ddocker16/docker-react npm run test